FROM debian:buster-slim

## install python3, add user 'utbot'
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
      python3-wheel && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  useradd -ms /bin/bash utbot

COPY ./ute /home/utbot/utecode/
RUN chown -R utbot:utbot /home/utbot
USER utbot
WORKDIR /home/utbot

CMD [ "python3", "/home/utbot/utecode/aggregator.py" ]
