## Global Settings
inbox_path: /ute/inbox
outbox_path: /ute/outbox
high_priority_folder_name: high
keep_source_file: True
completed_folder_name: done
vs_scripts_path: /ute/scripts/vs
file_poll_interval: 20
client_poll_interval: 30
log_level: info


## Database
##
## There should not be any reason to change these settings
db:
  results_poll_interval: 0.2
  client_tcp_keepalive: 600
  log_level: verbose
  db_save: False
  active_rehashing: False


## NFS Share Settings
nfs:
  server_address: 10.168.1.111
  mount_path: /mnt/user/work


# -----------------------------------------------------------------------------------
# You can override any/all of the below "task" settings by creating a new config file 
# with just the changes you want (maintain the below format) and placing it with the 
# video file you want to apply the settings to. 
#
# See UTE documentation for more details
# -----------------------------------------------------------------------------------


## Task Settings
##
## a 'task' represents all the information and state regarding the processing of a file 
## in UTE. these settings affect aspects of a task's encoding, muxing, subtitles, etc
task:
  job_size: 125
  frame_buffer_size: 100
  job_timeout: 600
  crop_sample_count: 17
  timeOffsetPercent: 0.15
  check_work_thread_count: 4
  find_work_thread_count_max: 16
  vapoursynth_enabled: False
  vs_script_name: denoise_best.py
  crop_detect: "24:16:0"


  # The arguments '-ss', '-hide_banner', and '-i', are reserved by 
  # UTE, and will be overwritten if present
  # 
  # UTE also adds '-filter:v "crop=<calulated value>"', as is calculated by the 
  # 'crop_config' section above. It can be overridden (along with all task settings) via
  # ".utconf.yml" config files co-located with the target video file
  #
  # Multiple lines are OK, but following lines must be indented past the 'ffmpeg' marker
  ffmpeg: ffmpeg -f yuv4mpegpipe -1 -loglevel fatal


  # UTE reserves the following arguments for use, and will overwrite these options if 
  # found:
  # '--frames', '--chunk-start', '--chunk-end', '--fps', and '-o'
  #
  # It is suggested to not use settings affecting how the encoder utilizes hardware 
  # resources, such as the '--pools' option in x265. If you want to affect how CPU 
  # resources are used, this is best done through granular settings in "docker-stack.yml".
  #
  # The resuling encoding string will be connected to FFMPEG via a pipe ('|') and work on
  # the data in a stream context
  #
  # Future releases may provide support for other encoders such as AV1
  #
  # Multiple lines are OK, but following lines must be indented past the 'encoder' marker
  encoder: x265 --log-level info --no-open-gop --colorprim bt709 --transfer bt709 
    --colormatrix bt709 --crf=26 --min-keyint 24 --keyint 240 --sar 1:1 --preset slow 
    --ctu 64 --y4m 





